apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-reverse-proxy-app
  name: udagram-reverse-proxy-app
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: udagram-reverse-proxy-app
  type: LoadBalancer 
