apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api-app
  labels:
    app: udagram-user-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-user-api-app
  template:
    metadata:
      labels:
        app: udagram-user-api-app
    spec:
      containers:
      - name: udagram-user-api-app
        image: femilawal/udagram-user-api
        ports:
        - containerPort: 8000