apiVersion: v1
kind: Service
metadata:
  name: udagram-user-api-app
  labels:
    app: udagram-user-api-app
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: udagram-user-api-app
  type: ClusterIP
status:
  loadBalancer: {}  