skip-check:
  - CKV_K8S_35: "Prefer using secrets as files over secrets as environment variables"
  - CKV_K8S_43: "Image should use digest" # Maintaining digest hashes is impractical for this project
  - CKV_K8S_14: "Image Tag should be fixed" # We use specific version tags, not latest
  - CKV_K8S_153: "Prevent All NGINX Ingress annotation snippets" # Required for security headers
