# Trivy Secret Detection Configuration
rules:
  - id: generic-api-key
    description: Generic API Key
    regex: '(?i)(api[_-]?key|apikey)["\s]*[:=]\s*["\']?([a-zA-Z0-9_\-]{20,})["\']?'
    allow:
      - description: "Example/placeholder keys"
        regex: '(your-.*-key|change-in-production|example|placeholder|test)'
      
  - id: jwt-secret
    description: JWT Secret
    regex: '(?i)(jwt[_-]?secret)["\s]*[:=]\s*["\']?([a-zA-Z0-9_\-]{10,})["\']?'
    allow:
      - description: "Development secrets"
        regex: '(your-super-secret|change-in-production)'

  - id: aws-credentials
    description: AWS Credentials
    regex: '(?i)(aws[_-]?secret[_-]?access[_-]?key|aws[_-]?access[_-]?key[_-]?id)["\s]*[:=]\s*["\']?([a-zA-Z0-9\/+=]{20,})["\']?'

  - id: database-password
    description: Database Password
    regex: '(?i)(postgres[_-]?password|db[_-]?password|database[_-]?password)["\s]*[:=]\s*["\']?([a-zA-Z0-9_\-!@#$%^&*]{8,})["\']?'
    allow:
      - description: "Environment variable references"
        regex: '\$\{.*\}'
      - description: "Development passwords"
        regex: '(udagram_password|password123|changeme)'

# Paths to skip scanning
skip-files:
  - ".git/**"
  - "node_modules/**"
  - "vendor/**"
  - "*.test.go"
  - "*_test.go"

skip-dirs:
  - ".git"
  - "node_modules"
  - "vendor"
