apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api-app
  namespace: default
  labels:
    app: udagram-feed-api-app
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: udagram-feed-api-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}   