apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend-app
  name: udagram-frontend-app    
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: udagram-frontend-app   
  type: LoadBalancer